export const INITIALIZED = 'nuke.INITIALIZED'
export const ROOT_CHANGED = 'nuke.ROOT_CHANGED'

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS'
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE'

export const FETCH_USERS = 'FETCH_USERS'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const BOOKMARK_POST = 'BOOKMARK_POST'
export const UNBOOKMARK_POST = 'UNBOOKMARK_POST'

export const SEARCH_INIT = 'SEARCH_INIT'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAILURE = 'SEARCH_FAILURE'

export const USER_LOGIN_INIT = 'USER_LOGIN_INIT'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'
export const USER_FROM_STORAGE = 'USER_FROM_STORAGE'

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN'
